# Generated by Django 4.2.4 on 2024-12-04 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_sale_price_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime(2024, 12, 4, 14, 54, 2, 497124), max_digits=6),
        ),
    ]
