# Generated by Django 4.2.4 on 2024-12-12 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime(2024, 12, 12, 23, 23, 9, 223842), max_digits=6),
        ),
    ]
